import React,{useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{Menu,Search,User,ShoppingBag,ChevronDown,ArrowRight,Truck,ShieldCheck,Headphones,Plus,Minus,X,Check,Package,BarChart3,Settings,LogOut,Eye,EyeOff}from'lucide-react';
import'./style.css';

const copy={
 da:{nav:['Produkter','Løsninger','Inspiration','Om os'],search:'Søg produkter',heroTag:'MESSEUDSTYR TIL HELE EUROPA',hero:'Bliv set. Bliv husket.',heroSub:'Professionelt messeudstyr, print og displays — produceret med omtanke og leveret direkte til din næste event.',shop:'Se alle produkter',talk:'Tal med en ekspert',popular:'Populære produkter',popularSub:'Alt du skal bruge for at skabe en stand, der tiltrækker opmærksomhed.',all:'Se hele sortimentet',add:'Læg i kurv',from:'Fra',why:'Derfor vælger brands Exposprint',delivery:'Levering i hele EU',deliverySub:'Direkte fra produktion til din adresse.',quality:'Kvalitet, der holder',qualitySub:'Gennemtestede materialer og skarpt print.',help:'Personlig rådgivning',helpSub:'Vi hjælper fra idé til færdig stand.',cta:'Har du en messe i kalenderen?',ctaSub:'Fortæl os om projektet — vi sammensætter den rigtige løsning og et uforpligtende tilbud.',quote:'Få et tilbud',cart:'Din kurv',empty:'Din kurv er tom',subtotal:'Subtotal',checkout:'Gå til betaling',login:'Log ind',email:'E-mail',password:'Adgangskode',loginBtn:'Log ind',demo:'Demo: admin@exposprint.eu / demo123',admin:'Administration',orders:'Ordrer',products:'Produkter',customers:'Kunder',revenue:'Omsætning',recent:'Seneste ordrer',continue:'Fortsæt med at handle'},
 en:{nav:['Products','Solutions','Inspiration','About'],search:'Search products',heroTag:'EXHIBITION EQUIPMENT ACROSS EUROPE',hero:'Get seen. Be remembered.',heroSub:'Professional exhibition equipment, print and displays — thoughtfully produced and delivered directly to your next event.',shop:'Shop products',talk:'Talk to an expert',popular:'Popular products',popularSub:'Everything you need to build a stand that gets attention.',all:'View full range',add:'Add to cart',from:'From',why:'Why brands choose Exposprint',delivery:'EU-wide delivery',deliverySub:'Directly from production to your address.',quality:'Quality that lasts',qualitySub:'Tested materials and pin-sharp print.',help:'Personal guidance',helpSub:'We help from first idea to finished stand.',cta:'Got an exhibition coming up?',ctaSub:'Tell us about your project — we will create the right solution and a no-obligation quote.',quote:'Get a quote',cart:'Your cart',empty:'Your cart is empty',subtotal:'Subtotal',checkout:'Proceed to checkout',login:'Sign in',email:'Email',password:'Password',loginBtn:'Sign in',demo:'Demo: admin@exposprint.eu / demo123',admin:'Administration',orders:'Orders',products:'Products',customers:'Customers',revenue:'Revenue',recent:'Recent orders',continue:'Continue shopping'},
 de:{nav:['Produkte','Lösungen','Inspiration','Über uns'],search:'Produkte suchen',heroTag:'MESSEAUSSTATTUNG IN GANZ EUROPA',hero:'Auffallen. In Erinnerung bleiben.',heroSub:'Professionelle Messeausstattung, Druck und Displays — sorgfältig produziert und direkt zu Ihrem nächsten Event geliefert.',shop:'Produkte entdecken',talk:'Experten sprechen',popular:'Beliebte Produkte',popularSub:'Alles, was Sie für einen aufmerksamkeitsstarken Messestand brauchen.',all:'Gesamtes Sortiment',add:'In den Warenkorb',from:'Ab',why:'Darum wählen Marken Exposprint',delivery:'EU-weite Lieferung',deliverySub:'Direkt von der Produktion zu Ihrer Adresse.',quality:'Qualität, die hält',qualitySub:'Geprüfte Materialien und gestochen scharfer Druck.',help:'Persönliche Beratung',helpSub:'Von der Idee bis zum fertigen Stand.',cta:'Eine Messe im Kalender?',ctaSub:'Erzählen Sie uns von Ihrem Projekt — wir erstellen die passende Lösung und ein unverbindliches Angebot.',quote:'Angebot erhalten',cart:'Ihr Warenkorb',empty:'Ihr Warenkorb ist leer',subtotal:'Zwischensumme',checkout:'Zur Kasse',login:'Anmelden',email:'E-Mail',password:'Passwort',loginBtn:'Anmelden',demo:'Demo: admin@exposprint.eu / demo123',admin:'Verwaltung',orders:'Bestellungen',products:'Produkte',customers:'Kunden',revenue:'Umsatz',recent:'Letzte Bestellungen',continue:'Weiter einkaufen'}
};
const products=[
 {id:1,name:'Roll-up Premium',price:119,cat:'Roll-ups',color:'#d8dfd8',art:'roll'},
 {id:2,name:'Textile Wall 3×2,3 m',price:489,cat:'Textile displays',color:'#e6d9cd',art:'wall'},
 {id:3,name:'Messebord Curve',price:239,cat:'Counters',color:'#cfd8db',art:'desk'},
 {id:4,name:'Beachflag Drop',price:99,cat:'Outdoor',color:'#e5dfcd',art:'flag'}
];
function Art({type}){return <div className={'art '+type}><i/><b>EXPO<br/>PRINT</b><em/></div>}
function App(){const[lang,setLang]=useState('da'),[cart,setCart]=useState([]),[panel,setPanel]=useState(null),[logged,setLogged]=useState(false),[showPass,setShowPass]=useState(false);const t=copy[lang];const total=useMemo(()=>cart.reduce((a,x)=>a+x.price*x.qty,0),[cart]);const add=p=>setCart(c=>{let x=c.find(i=>i.id===p.id);return x?c.map(i=>i.id===p.id?{...i,qty:i.qty+1}:i):[...c,{...p,qty:1}]});const qty=(id,n)=>setCart(c=>c.map(x=>x.id===id?{...x,qty:x.qty+n}:x).filter(x=>x.qty));function login(e){e.preventDefault();setLogged(true);setPanel('admin')}
return <><header><a className="logo">EXPOS<span>PRINT</span></a><nav>{t.nav.map((x,i)=><a key={x}>{x}{i<2&&<ChevronDown/>}</a>)}</nav><div className="tools"><button aria-label="Search"><Search/></button><select value={lang} onChange={e=>setLang(e.target.value)}><option value="da">DA</option><option value="en">EN</option><option value="de">DE</option></select><button onClick={()=>setPanel('login')}><User/></button><button className="bag" onClick={()=>setPanel('cart')}><ShoppingBag/><sup>{cart.reduce((a,x)=>a+x.qty,0)}</sup></button><button className="mobile"><Menu/></button></div></header>
<main><section className="hero"><div className="heroCopy"><small>{t.heroTag}</small><h1>{t.hero}</h1><p>{t.heroSub}</p><div><button className="primary" onClick={()=>document.querySelector('#products').scrollIntoView()}>{t.shop}<ArrowRight/></button><button className="link">{t.talk}<ArrowRight/></button></div></div><div className="scene"><div className="arch">EXPO<br/><span>SPRINT</span></div><div className="plant">✦<br/>╱╲</div><div className="counter">MAKE<br/>AN IMPACT</div><div className="floor"/></div></section>
<section className="trust"><div>4.8 <span>★★★★★</span><small>Trustpilot</small></div><p>Trusted by 2,000+ European brands</p><div className="brands"><b>NORDIC</b><b>muto</b><b>HELLO!</b><b>ARC</b></div></section>
<section className="products" id="products"><div className="sectionHead"><div><small>SHOP THE ESSENTIALS</small><h2>{t.popular}</h2><p>{t.popularSub}</p></div><button className="link">{t.all}<ArrowRight/></button></div><div className="grid">{products.map(p=><article key={p.id}><div className="visual" style={{background:p.color}}><span>{p.cat}</span><Art type={p.art}/></div><h3>{p.name}</h3><div className="productBottom"><p>{t.from} <strong>€{p.price},00</strong></p><button onClick={()=>add(p)}><Plus/> {t.add}</button></div></article>)}</div></section>
<section className="benefits"><h2>{t.why}</h2><div><Benefit icon={<Truck/>} title={t.delivery} text={t.deliverySub}/><Benefit icon={<ShieldCheck/>} title={t.quality} text={t.qualitySub}/><Benefit icon={<Headphones/>} title={t.help} text={t.helpSub}/></div></section>
<section className="cta"><small>LET'S CREATE SOMETHING</small><h2>{t.cta}</h2><p>{t.ctaSub}</p><button className="light">{t.quote}<ArrowRight/></button></section></main>
<footer><a className="logo inverse">EXPOS<span>PRINT</span></a><p>Exhibition equipment that makes brands impossible to ignore.</p><div>© 2026 Exposprint Europe · Terms · Privacy · VAT</div></footer>
{panel&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&setPanel(null)}><aside className={panel==='admin'?'admin':''}><button className="close" onClick={()=>setPanel(null)}><X/></button>{panel==='cart'&&<Cart t={t} cart={cart} qty={qty} total={total}/>} {panel==='login'&&<Login t={t} login={login} show={showPass} setShow={setShowPass}/>} {panel==='admin'&&<Admin t={t} logout={()=>{setLogged(false);setPanel(null)}}/>}</aside></div>}
</>}
function Benefit({icon,title,text}){return <article><i>{icon}</i><h3>{title}</h3><p>{text}</p></article>}
function Cart({t,cart,qty,total}){return <div className="drawer"><h2>{t.cart}</h2>{!cart.length?<div className="empty"><ShoppingBag/><p>{t.empty}</p><button>{t.continue}</button></div>:<><div>{cart.map(x=><div className="cartItem" key={x.id}><div className="thumb" style={{background:x.color}}><Art type={x.art}/></div><section><b>{x.name}</b><small>€{x.price},00</small><div><button onClick={()=>qty(x.id,-1)}><Minus/></button>{x.qty}<button onClick={()=>qty(x.id,1)}><Plus/></button></div></section><strong>€{x.price*x.qty},00</strong></div>)}</div><div className="total"><span>{t.subtotal}</span><b>€{total},00</b></div><button className="primary checkout" onClick={()=>alert('Secure checkout ready for Stripe integration')}>{t.checkout}<ArrowRight/></button></>}</div>}
function Login({t,login,show,setShow}){return <div className="login"><small>EXPOSPRINT ACCOUNT</small><h2>{t.login}</h2><p>Access orders, invoices and saved designs.</p><form onSubmit={login}><label>{t.email}<input type="email" defaultValue="admin@exposprint.eu" required/></label><label>{t.password}<span><input type={show?'text':'password'} defaultValue="demo123" required/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></span></label><button className="primary">{t.loginBtn}<ArrowRight/></button></form><em>{t.demo}</em></div>}
function Admin({t,logout}){return <div className="adminPage"><div className="adminTop"><div><small>EXPOSPRINT</small><h2>{t.admin}</h2></div><button onClick={logout}><LogOut/> Log out</button></div><div className="adminNav"><button className="active"><BarChart3/> Overview</button><button><Package/> {t.orders}</button><button><ShoppingBag/> {t.products}</button><button><User/> {t.customers}</button><button><Settings/> Settings</button></div><div className="stats"><article><small>{t.revenue}</small><b>€48,290</b><span>↗ 12.4%</span></article><article><small>{t.orders}</small><b>184</b><span>↗ 8.1%</span></article><article><small>{t.customers}</small><b>1,248</b><span>↗ 5.7%</span></article></div><div className="orders"><h3>{t.recent}</h3>{[['#EP-1048','Atelier Nord','€1,248','Processing'],['#EP-1047','Studio Forma','€489','Shipped'],['#EP-1046','Messewerk GmbH','€2,390','Delivered']].map(r=><div>{r.map((x,i)=><span className={i===3?'status':''}>{x}</span>)}</div>)}</div></div>}
createRoot(document.getElementById('root')).render(<App/>);
